[book]
authors = ["Gábor Szabó"]
language = "en"
multilingual = false
src = "src"
title = "The Axum book"
description = ""

# Add github icon to the menu
[output.html]
git-repository-icon = "fa-github"
#git-repository-url = "https://github.com/tokio-rs/axum"
#edit-url-template = "https://github.com/tokio-rs/axum/edit/main/book/{path}"
git-repository-url = "https://github.com/szabgab/axum/tree/book"
edit-url-template = "https://github.com/szabgab/axum/blob/book/book/{path}"

# Embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by the authors"

